# Generated by Django 5.0.6 on 2025-10-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemApp', '0002_alter_mesa_options_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('mesa', 'fecha', 'hora'), name='uniq_reserva_mesa_fecha_hora'),
        ),
    ]
